// Copyright (C) 2021, 2022 by Mark Melton
//

#pragma once
#include "coro/stream/adapt.h"
#include "coro/stream/alternate.h"
#include "coro/stream/apply.h"
#include "coro/stream/chaining.h"
#include "coro/stream/choose.h"
#include "coro/stream/collect.h"
#include "coro/stream/draw.h"
#include "coro/stream/filter.h"
#include "coro/stream/flatten.h"
#include "coro/stream/group.h"
#include "coro/stream/group_tuple.h"
//#include "coro/stream/io/read_lines.h"
//#include "coro/stream/io/write_lines.h"
#include "coro/stream/iota.h"
#include "coro/stream/once.h"
#include "coro/stream/range.h"
#include "coro/stream/reduce.h"
#include "coro/stream/repeat.h"
#include "coro/stream/sampler/all.h"
#include "coro/stream/sequence.h"
#include "coro/stream/take.h"
#include "coro/stream/transform.h"
#include "coro/stream/unique.h"
#include "coro/stream/zip.h"
